### ISSUE TITLE
Matrices for time series-one condition

### ISSUE THREAD

**Issue by alabastida1** [eturro/mmseq#11]
Dear developer,
I have a RNA-seq experimental design consisting of two individuals (biological replicates), who were sampled at 24, 48, 72, 96 and 120 hours after receiving a treatment. Could you be so kind to give me some advice on how to write the corresponding matrices file?

**Comment by eturro** [comment]
Hi

It depends on which patterns you wish to identify. If you would like to compare a model in which the expression is independent of time point with one in which each time point has a different mean expression level, then the easiest thing would be to use the -de option (-de 2 2 2 2 2 and then list the pairs of mmseq files for each time point).

If you would like to fit a model specifying a trend over time (e.g. linear), then you could use a matrices file containing the following

# M; no. of rows = no. of observations
0
0
0
0
0
0
0
0
0
0
# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
0 1
0 1
0 2
0 2
0 3
0 3
0 4
0 4
# P0(collapsed); no. of rows = no. of classes for model 0
1
# P1(collapsed); no. of rows = no. of classes for model 1
0
1
2
3
4

In the mmdiff output, eta1_0 would represent the estimated log fold change between successive time points.

You can of course compare the three models (single mean, independent time-specific means and time-specific means following a pre-specified trend) together by running both of the pairwise comparisons mentioned above and then following the instructions on polytomous classification.

Hope this helps

Ernest

**Comment by alabastida1** [comment]
Thank you for your detailed answer Ernest,

This answers my question perfectly. 

Aurora
