### ISSUE TITLE
Matrices for time series-two conditions

### ISSUE THREAD

**Issue by alabastida1** [eturro/mmseq#12]
Hi Ernest,

Could you please tell me which matrices to use for the following RNA-seq experimental design and model comparison?:

I have two parallel time-series, one for Treated individuals and one for Control individuals (two replicates each):

Time|Control|Treated
------|--------------|----------
t0|2 replicates|2 rep
t1|2 rep|2 rep
t2|2 rep|2 rep

My goal is to identify those transcripts (or genes) whose linear expression trend over time is different in the treated and the untreated individuals. To put it in another way:

```
    model 1          model 0
expression       expression
    |*               |
    |    *   +       |        *+         * treated sample
    |    +   *       |    *+             + control sample
    |+               |*+    
    |__________time  |__________ time
     t0  t1  t2       t0  t1  t2
    6 classes?       3 classes?
```
In model 1 the slope and/or intersection of the treated and control trends would be different, while in model 0 they would be the same.

By now I have two alternative ideas on how to build the corresponding M and P matrices:

&nbsp;&nbsp;&nbsp;&nbsp;A) M would contain a single class (12 zeroes), and P would have two columns, each one of them depicting the 3 and 6 classes of models 0 and 1, respectively. 
&nbsp;&nbsp;&nbsp;&nbsp;B) The P matrix will only depict the 3 classes corresponding to time, while the treated/control conditions would be represented as two classes in the M matrix.

**I am not sure about the content of the P0 and P1 matrices for any of the two cases**

I have found it difficult to understand the principles underlying the construction of this matrices, but I am willing to consult any material that you might suggest.

Aurora

**Comment by eturro** [comment]
Dear Aurora

The M matrix is used for encoding the effect of model-independent covariates. I don't think that is required here, so you can keep that to 12 zeros as you suggest.

You then have to encode the design matrix under model 0 (P0) and under model 1 (P1). I'll assume you have ordered your samples by condition and then by time point.

One way to do this in the matrices file is as follows (I'm skipping the # M section for conciseness):

# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
1 1
1 1
2 2
2 2
3 3
3 3
4 4
4 4
5 5
6 6
# P0(collapsed); no. of rows = no. of classes for model 0
-.5 0
-.5 1
-.5 2
0.5 0
0.5 1
0.5 2
# P1(collapsed); no. of rows = no. of classes for model 1
-.5 0 0
-.5 1 0
-.5 2 0
0.5 0 0
0.5 0 1
0.5 0 2

This would lead to:

P0:
1 -.5 0
1 -.5 0
1 -.5 1
1 -.5 1
1 -.5 2
1 -.5 2
1 0.5 0
1 0.5 0
1 0.5 1
1 0.5 1
1 0.5 2
1 0.5 2

P1:
1 -.5 0 0
1 -.5 0 0
1 -.5 1 0
1 -.5 1 0
1 -.5 2 0
1 -.5 2 0
1 0.5 0 0
1 0.5 0 0
1 0.5 0 1
1 0.5 0 1
1 0.5 0 2
1 0.5 0 2

As you can see both models have a global intercept (alpha0 and alpha1). Model 0 has eta0_0, which encodes the fold change between the two conditions and eta0_1, which encodes the fold change between successive time points. Model 1 would have eta1_0 (same role as eta0_0), but then eta1_1 would encode the fold change between successive time points in condition 0 and eta1_2 would encode the fold change between successive time points in condition 1.

This would work as is but it might be better to compare each of these models separately to a baseline model that simply has a separate mean for each condition, without a time trend. I.e.:

Comparison 1:

# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
0 1
0 1
0 2
0 2
1 3
1 3
1 4
1 4
1 5
1 6
# P0(collapsed); no. of rows = no. of classes for model 0
-.5
-.5
-.5
0.5
0.5
0.5
# P1(collapsed); no. of rows = no. of classes for model 1
-.5 0
-.5 1
-.5 2
0.5 0
0.5 1
0.5 2

Comparison 2:

# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
0 1
0 1
0 2
0 2
1 3
1 3
1 4
1 4
1 5
1 6
# P0(collapsed); no. of rows = no. of classes for model 0
-.5
-.5
-.5
0.5
0.5
0.5
# P1(collapsed); no. of rows = no. of classes for model 1
-.5 0 0
-.5 1 0
-.5 2 0
0.5 0 0
0.5 0 1
0.5 0 2

And then use the polyclass() function to compare the three models together as per the documentation, ensuring you have specified appropriate prior probabilities for each one.

Best wishes
Ernest

**Comment by alabastida1** [comment]
Once again thank you for your accurate explanation Ernest, this solves my doubts.
Best,
Aurora
