### ISSUE TITLE
how to supply regex for bam2hits with single sequence name?

### ISSUE THREAD

**Issue by n-long** [eturro/mmseq#13]
Hello,

All of my sequence headers share a single word format such as GENE_strain. I added a gene and transcript identifier originally, but my read mapping failed when using '--fullref' argument to bowtie1 using tophat (you can add all of the arguments at around line 2349 in the tophat executable). I had to go that route since using bowtie as provided in the manual was not producing a proper SAM alignment format, despite correct flags. Anyway, all my gene and transcript identifiers are 1:1 anyway, but I cannot figure out the regex pattern to make bam2hits assign the sequence header to both identifiers.

I've gotten this far but I can't get past a segfault. 
bam2hits -m \"(\S+)\" 1 1

Thanks.

**Comment by eturro** [comment]
> bowtie as provided in the manual was not producing a proper SAM alignment format, despite correct flags
> 
Hi,
I think we should get to the bottom of this first as tophat is designed for alignment to the genome (with spliced alignments), not alignment to a transcriptome.

What exactly is the problem with running bowtie1? Could you expand on this please ? I've been using it for years without a problem.

Many thanks

**Comment by n-long** [comment]
Thank you for the response! I am using bowtie 1.1.2 and samtools 1.2. I have error corrected my reads using bfc and followed your instructions exactly for trim_galore (my reads are 100bp illumina)

bowtie -a --best --strata -S -m 100 --norc --chunkmbs 256 -p 4 hybrid_master -1 bfc_1p1n.1_val_1.fq -2 bfc_1p1n.2_val_2.fq | samtools view -F 0xC -b - > 1p1n_namesorted

[W::sam_read1] parse error at line 34162
[main_samview] truncated file.
Error while flushing and closing output
terminate called after throwing an instance of 'int'

the first 34160 lines are the sequence dictionary, so the error is right when alignment begins

`@PG	ID:Bowtie	VN:1.1.2	CL:"bowtie --wrapper basic-0 -a --best --strata -S -m 100 --norc --chunkmbs 256 -p 24 hybrid_master -1 bfc_1p1n.1_val_1.fq -2 bfc_1p1n.2_val_2.fq"
HWI-1KL138:1:1101:1128:1920#ATCACGATCACG/1	77	*	0	0	*	*	0	0	CTTGTAGGGACAGAAATAAAATTTTCCCATCAACTTCGTACTGTCCGATAAACATTAGACTATCGGCGTGGAACGTGGGATCAAACTAGGCTTGGTTAA	&?????????????????#??????????????????????????????????????????????????????"?"???????????????????????	XM:i:0
HWI-1KL138:1:1101:1128:1920#ATCACGATCACG/2	ec:Z:5	141	*	0	0	*	*	0	0	GTAACATTTAGTGGTTGCTTTTGCTACAGATTCATGCATTTGTGCATTGTCGCATCCCGATTACATCAAACCGTGCTACCTCTAAATGACCGTTTTTAA	OGG[G[]S_U_M_ZQ__X^^\SM__SHQQHM_SH_R]_^WR\QHP\]^W^BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB	XM:i:0
HWI-1KL138:1:1101:1111:1981#ATCACGATCACG/1	77	*	0	0	*	*	0	0	TTGGCGGTATGTACCGGTTCGGACTTCGTCGACGACTGTTGGCTCCAAGTCGACAAAAACGGCCCTCGGGACGTGTTTTCCGGCGCCAGTTTCGCTGAA	#????????????????????????$???$???%????????????????????????????????%??????????????%?????????????$?$?	XM:i:0
HWI-1KL138:1:1101:1111:1981#ATCACGATCACG/2	ec:Z:3	141	*	0	0	*	*	0	0	CGCGGTTTCAAATCCAAAATCATGATGTAATGCATTTCCGGCGACATTGGCCAAGCCGGTTTCCAGATTGTCAACGGCCGTTGGGAACTCTACTGTCTG	JJP_J^`H[`a`SJ^]J^bV`_bSJJQQQ^^Y_I_`\^`BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB	XM:i:0`

**Comment by n-long** [comment]
Interestingly, the same bowtie command works on the raw fastq sequence files if I do not include the '--fullref' option

here are the sequence headers for my transcript reference

`>TC002292_des	gene:TC002292_des	transcript:TC002292_des
>TC002291_des	gene:TC002291_des	transcript:TC002291_des
>TC002290_des	gene:TC002290_des	transcript:TC002290_des
>TC002293_des	gene:TC002293_des	transcript:TC002293_des
>TC002289_des	gene:TC002289_des	transcript:TC002289_des
>TC002294_des	gene:TC002294_des	transcript:TC002294_des
>TC002288_des	gene:TC002288_des	transcript:TC002288_des
>TC002287_des	gene:TC002287_des	transcript:TC002287_des
>TC002286_des	gene:TC002286_des	transcript:TC002286_des
>TC002285_des	gene:TC002285_des	transcript:TC002285_des`

**Comment by eturro** [comment]
If you share the files with me in private (the fastq pair  (or just as many lines as needed to reproduce the error) and the reference fasta you are aligning to) I can try to figure out what is going on with bowtie1. As I say I've tested it thoroughly over the years so I doubt it's a bug

Thanks

**Comment by eturro** [comment]
For the record, this issue was resolved by email in private

- You can't have the error correction tags in the FASTQ header lines. They can be removed like this: `awk '{print $1}' sample.1.fq > sample_.1.fq`
- You can't have tab characters in the reference fasta headers as these are are transcribed into the SAM output, which actually uses tabs to delineate entries. Converting the tabs to spaces can be done like this: `sed -E "s/\t/ /g" ref_with_tabs.fa > ref_with_spaces.fa`
- The standard regexp worked fine, "(\S+).*gene:(\S+).*", with transcript index 1 and gene index 2
- Regarding the threshold, I suggest looking at the distribution of the "posterior_probability" values. You should see a small number of features that rise up well above twice the prior (i.e. > 0.2, by default). That should give reasonable results. In theory the FDR is the mean of 1-posterior_probability of the selected transcripts above a particular threshold, but that assumes that the posterior probabilities are well calibrated, so I wouldn't rely on this notion too much.
