### ISSUE TITLE
High percentage of reads are not mapping

### ISSUE THREAD

**Issue by abhisheksinghnl** [eturro/mmseq#15]
Hi,

This might not be the right place to put this up but I will appreciate if someone can help me.

I have single end RNA-seq data and when I align that data using bowtie1 by following command

`zcat lane8_E18_3_CGATGT_L008_R1.fastq.gz | ~/Softwares/MMseq/bowtie-1.1.2/bowtie -a --best --strata -S -m 100 -X 500 --chunkmbs 256 -p 8 ~/Softwares/MMseq/mmseq-latest/Rat6ref/new/Rattus_norvegicus.Rnor_6.0.ref_transcripts - | samtools view -F 0xC -bS - | samtools sort -n - > E18_1`

```
# reads processed: 27452186
# reads with at least one reported alignment: 4384153 (15.97%)
# reads that failed to align: 23064807 (84.02%)
# reads with alignments suppressed due to -m: 3226 (0.01%)
Reported 18182347 alignments to 1 output stream(s)
[bam_sort_core] merging from 8 files...

```

Only 15% of reads map,  is this normal?

What shall I do, to get better mapping? Does this have to do something with parameters of bowtie or it is just my data is shit.

Thank you

**Comment by eturro** [comment]
Hi,

These possibilities come to mind:

1) The data are not primarily from genic regions of the rat genome
2) The data are not primarily from rat
3) The data have many sequence errors

I would suggest aligning to the rat genome (e.g. using STAR) and checking that you also get a low alignment rate in that case, to ensure that it's not 1).
You could use a multi-species alignment package to check it's not 2).
Have a good inspection of the raw data to investigate 3).

best wishes
Ernest
