### ISSUE TITLE
Editing reference file

### ISSUE THREAD

**Issue by abhisheksinghnl** [eturro/mmseq#16]
Hi,

I am working with Rat genome and I have downloaded the files cdna and ncrna as directed and followed the steps of merging them together but I did not filter them for anySuper contig or haplotype using fastagrep.sh.

However, all the genome alignment and everything went fine, but I get the gene Ids/feature Id as:

  ```
ENSRNOG00000000001.5
  ENSRNOG00000000007.7
  ENSRNOG00000000008.7
  ENSRNOG00000000009.5


feature_id	log_mu	sd	mcse	iact	effective_length	true_length	unique_hits	ntranscripts	observed	percentiles5,25,50,75,95
ENSRNOG00000000001.5	-11.9754	10.5222	0.328819	1	1237	NA	0	1	0	1.28257e-14,1.14878e-07,0.000147833,0.00841203,0.149571
ENSRNOG00000000007.7	-4.31787	2.62437	0.0820116	1	1758.2	NA	0	4	0	9.38522e-05,0.00341925,0.0229834,0.0856848,0.341789
ENSRNOG00000000008.7	0.469715	0.361166	0.0106912	0.897298	1568	NA	8	1	1	0.883641,1.26489,1.62147,2.05065,2.75036
ENSRNOG00000000009.5	-11.5155	9.9814	0.311919	1	1182	NA	0	1	0	1.44401e-14,2.84568e-07,0.000241538,0.00899963,0.159891
ENSRNOG00000000010.5	-11.7032	9.00453	0.281392	1	2265	NA	0	1	0	1.0683e-13,1.63457e-07,0.000137861,0.00509959,0.0691979
ENSRNOG00000000012.5	0.763521	0.429914	0.0134396	1.00072	814	NA	6	1	1	1.04263,1.64183,2.23023,2.92813,4.18205
ENSRNOG00000000017.7	-12.0851	11.0173	0.344292	1	1101	NA	0	1	0	1.37857e-15,1.36881e-07,0.000152784,0.00878132,0.139119
ENSRNOG00000000021.3	1.7313	0.238328	0.00781276	1.10042	1021	NA	19	1	1	3.73811,4.85222,5.74354,6.68997,8.16492

```

Could you please let me know, why is this happening.

Also, I have single end data and not paired end.

Thank you

Best regards

**Comment by eturro** [comment]
Hi,

> However, all the genome alignment and everything went fine

You mean alignment to the transcriptome (merged cDNA and ncRNA files), not the genome.

>  but I get the gene Ids/feature Id as:
> 
> ENSRNOG00000000001.5
>   ENSRNOG00000000007.7
>   ENSRNOG00000000008.7
>   ENSRNOG00000000009.5


What do you perceive to be the problem with the IDs that you mention? They are standard transcript IDs, as can be seen on the Ensembl web site, e.g.:

http://www.ensembl.org/Rattus_norvegicus/Transcript/Summary?db=core;g=ENSRNOG00000000001;r=2:230660664-230662084;t=ENSRNOT00000055633

So you have expression quantification for every rat transcript.

In the *.gene.mmesq file you will find the corresponding gene-level expression estimates (i.e. for ENSRNOG00000000001, etc).

best
Ernest

**Comment by abhisheksinghnl** [comment]
Hi,

Thank you for the explaination, I was wondering about this decimal part.

Best
Abhishek

**Comment by eturro** [comment]
These integers after the full stop represent versions and were introduced in Ensembl 85:

> Transcript version display (all species)
> 
> You can now see the transcript's version displayed alongside the transcript stable ID on the transcript table and inside the zmenu

From http://www.ensembl.org/info/website/news.html?id=85

They appear to have been added to the FASTA file identifiers somewhere in a recent release too (release 83, I think; though this is not in the release notes).

Personally, I think this decision just adds clutter and no doubt will break one or two pipelines.

**Comment by abhisheksinghnl** [comment]
Hi,

One additional question, how can I make a matrix for 7 groups each with 3 replicates.

A little help will be highly appreciated.

Thank you

**Comment by eturro** [comment]
If you wish to compare a model in which there is a global mean to one in which each group has its own mean, then just use the -de option (-de 3 3 3 3 3 3 3)

**Comment by abhisheksinghnl** [comment]
Hi,

Thank you for your reply.

Once I have this output I will still get the expression across the whole
trancriptome and I am interested in getting the expression of the ones that
demarcate one time point from the others. How can I filter this list?

A little help will be useful at this point.

Thank you

Best regards
Abhishek
