### ISSUE TITLE
Gene ID to Gene name

### ISSUE THREAD

**Issue by abhisheksinghnl** [eturro/mmseq#20]
Hi,

Not completely related to MMSeq but you may know the way out of this situation.

I am using GRCh37.70 genome build of ensembl and I get gene IDs for log_mu's. Now, Iwould like to convert these gene Ids to gene name. I have tried biomart but it is taking me to ensembl genes 86 (GRCh37.p13). Is this correct?

Thank you

**Comment by eturro** [comment]
Unfortunately, version 70 is no longer in the Ensembl archives. It is a bit frustrating that they remove old versions.

The closest you can get right now is version 74:

library(biomaRt)
ensembl <- useMart(host="dec2013.archive.ensembl.org", biomart="ENSEMBL_MART_ENSEMBL",dataset="hsapiens_gene_ensembl")
annot<-getBM(c("ensembl_gene_id", "external_gene_id"), mart=ensembl)
head(annot)

  ensembl_gene_id external_gene_id
1 ENSG00000261657         SLC25A26
2 ENSG00000223116       AL157931.1
3 ENSG00000233440          HMGA1P6
4 ENSG00000207157           RNY3P4
5 ENSG00000229483        LINC00362
6 ENSG00000252952         RNU6-58P

**Comment by abhisheksinghnl** [comment]
Hi,

Indeed it is very frustrating. May I use these as corresponding gene names?

Thank you

Best regards
Abhishek

**Comment by eturro** [comment]
Yes but it is possible that you will find that some of your ENSG's are missing from this 'anno' table if they were retired between version 70 and version 74

PS. you could put in a request with Ensembl for keeping all archive versions; if enough people make a fuss maybe they'll change their policy

**Comment by abhisheksinghnl** [comment]
Hi,

Email has been sent to them. Will update you on their response.

Thank you.

Best regards
Abhishek

**Comment by eturro** [comment]
The strongest argument for maintaining them is reproducible research. If you have some code (e.g. for a paper) that uses a particular version of Ensembl to process some data, then that version of Ensembl must remain accessible for results to be reproducible in the future, unless you've remembered to save the downloaded data separately.

**Comment by abhisheksinghnl** [comment]
Here is the reply (not an official one) but still solves the problem. https://www.biostars.org/p/217899/#218101

**Comment by eturro** [comment]
Yes, I can confirm you can use the GTF files instead and they will match the biomaRt table:

# with biomaRt
library(biomaRt)
ensembl <- useMart(host="feb2014.archive.ensembl.org", biomart="ENSEMBL_MART_ENSEMBL",dataset="hsapiens_gene_ensembl")
annot<-getBM(c("ensembl_gene_id", "external_gene_id"), mart=ensembl)

# using GTF 
gtf=read.table("Homo_sapiens.GRCh37.75.gtf.gz",sep="\t",comment.char="#") # from Ensembl FTP server
gtf=gtf[gtf[,3]=="gene",]
gtf.anno=do.call(rbind,lapply(strsplit(sapply(gtf[,9],as.character), ";") , function(x) { gid=strsplit(x[grep("gene_id", x)]," ")[[1]][2]; gn=strsplit(x[grep("gene_name", x)]," ")[[1]][3]; return(c(gid,gn)) }))

# check match
annot=annot[grep("LRG",annot[,1],invert=TRUE),] # LRG records are not in the GTF
annot=cbind(annot,gene.gtf=gtf.anno[match(annot[,1], gtf.anno[,1]),2])
head(annot)

  ensembl_gene_id external_gene_id   gene.gtf
1 ENSG00000261657         SLC25A26   SLC25A26
2 ENSG00000223116       AL157931.1 AL157931.1
3 ENSG00000233440          HMGA1P6    HMGA1P6
4 ENSG00000207157           RNY3P4     RNY3P4
5 ENSG00000229483        LINC00362  LINC00362
6 ENSG00000252952         RNU6-58P   RNU6-58P


all(annot[,2]==annot[,3])

TRUE
