### ISSUE TITLE
Interpretation of a model for assessing the fold-change difference between two pairs of groups 

### ISSUE THREAD

**Issue by ndrubins** [eturro/mmseq#22]
Hi,

I'm trying to follow the example for assessing whether the log fold change between group A and group B is different (as opposed to equal) to the log fold change between group C and group D. In my case it is testing whether the fold change between treatment and control in group 2 is different from that in group 2. I.e. is log((group1.treatment/group1.control)/(group2.treatment/group2.control)) significantly different from 0.

The matrix I'm using is identical to that given in the [https://raw.githubusercontent.com/eturro/mmseq/master/doc/dod2.mat](url). What I'm unsure of is the order of groups I need to provide to mmdiff and the interpretation of the output.

What I'm currently doing is calling mmdiff this way:
`mmdiff -m matrices_file group1.treatment.rep1.mmseq group1.treatment.rep2.mmseq group1.control.rep1.mmseq group1.control.rep2.mmseq group2.treatment.rep1.mmseq group2.treatment.rep2.mmseq group2.control.rep1.mmseq group2.control.rep2.mmseq  > out.mmdiff
`
Looking at the output eta1_1 and eta1_2 look well correlated with ln(mean(exp(group1.treatment.rep1.mmseq),exp(group1.treatment.rep2.mmseq))/mean(exp(group1.control.rep1.mmseq),exp(group1.control.rep2.mmseq))) and ln(mean(exp(group2.treatment.rep1.mmseq),exp(group2.treatment.rep2.mmseq))/mean(exp(group2.control.rep1.mmseq),exp(group2.control.rep2.mmseq))), respectively, so I guess the order in which I specified the input files to mmdiff is correct. However, when I look at the correlation between:
eta1_0 and
ln((mean(exp(group1.treatment.rep1.mmseq),exp(group1.treatment.rep2.mmseq))/mean(exp(group1.control.rep1.mmseq),exp(group1.control.rep2.mmseq)))/(mean(exp(group2.treatment.rep1.mmseq),exp(group2.treatment.rep2.mmseq))/mean(exp(group2.control.rep1.mmseq),exp(group2.control.rep2.mmseq))))

it doesn't look that strong. In addition, the scale of eta1_0 seems significantly larger than that of eta1_1/eta1_2.  A few lines for example:

eta1_0   eta1_1   eta1_2
-3.34    0.33     0.35
9.2        0.36     -0.84
-3.37    0.13      0.35

Any idea?

**Comment by eturro** [comment]
Hello

the eta1_* values are only interpretable if posterior_probability is high. Therefore, when exploring the output, first threshold on posterior_probability and then look at the eta1_* values.

Under the alternate model (model 1), the interpretation of each parameters is as follows:

eta1_0: log FC between group1 and group 2
eta1_1: log FC between treatment and control in group 1
eta1_2: log FC between treatment and control in group 2

I hope this helps

**Comment by ndrubins** [comment]
Hi @eturro,

Thanks a lot for the quick response.

Here are a few lines from the mmdiff output, ordered descendingly first by Bayes factor and then by posterior probability, and here are the top 15 transcripts:

bayes_factor	posterior_probability	alpha0	beta0_0	beta0_1	eta0_0	eta0_1	alpha1	beta1_0	beta1_1	eta1_0	eta1_1	eta1_2	mu_group1.treatment_1	mu_group1.treatment_2	mu_group1.treatment_3	mu_group1.control_1	mu_group1.control_2	mu_group1.control_3	mu_group2.treatment_1	mu_group2.treatment_2	mu_group2.treatment_3	mu_group2.control_1	mu_group2.control_2	mu_group2.control_3	sd_group1.treatment_1	sd_group1.treatment_2	sd_group1.treatment_3	sd_group1.control_1	sd_group1.control_2	sd_group1.control_3	sd_group2.treatment_1	sd_group2.treatment_2	sd_group2.treatment_3	sd_group2.control_1	sd_group2.control_2	sd_group2.control_3
1167.41	0.99235	-0.88241	0.00853576	0.0149539	2.69926	1.21969	-1.09857	0.0275615	-0.0466063	3.56875	0.325802	3.81669	0.745461	0.975005	0.87384	0.666482	0.545429	0.342952	-0.946853	-1.24812	-0.744486	-4.85837	-4.77283	-4.82293	0.110776	0.101046	0.11563	0.104278	0.113547	0.132975	0.313321	0.568584	0.478553	0	0	0
793.278	0.988782	-0.59125	-0.0285857	-0.138759	6.19519	0.609406	-0.549705	0.0200247	-0.0470306	6.27052	-0.178504	2.25072	2.53559	2.54136	2.41319	2.67373	2.69597	2.67199	-3.21833	-2.14171	-2.39481	-4.85837	-4.77283	-4.82293	0.0354028	0.0337218	0.0406328	0.0296006	0.0294458	0.0309646	0.531058	0.411192	0.460555	0	0	0
767.53	0.98841	-1.16449	0.164631	-0.18832	-5.23337	0.190394	-1.07425	0.125133	-0.0811387	-5.40029	2.43308	-0.980819	-3.03336	-1.84385	-2.86073	-5.07554	-4.96564	-5.01829	1.2556	1.18955	0.934143	2.19439	2.24615	1.97422	0.857503	0.575725	0.884274	0	0	0	0.0912775	0.10635	0.115812	0.0503048	0.0490014	0.0594306
734.112	0.987889	1.62628	0.117521	-0.0479972	7.57611	0.4597	1.51966	0.123575	-0.0259141	8.08109	-0.449734	4.4589	5.66687	5.29347	5.04328	6.04893	5.76721	5.65863	-1.02787	0.238131	-0.0449494	-4.85837	-4.77283	-4.82293	0.0134028	0.0160775	0.0198606	0.00964972	0.0122687	0.0124042	0.341516	0.202248	0.23018	0	0	0
684.172	0.987016	1.66604	0.130948	-0.0665243	-0.993498	0.593318	1.61334	0.111257	-0.0463632	-1.39905	2.09433	-0.431892	1.86014	2.06722	2.00885	-0.103762	0.105503	-0.829846	2.20663	2.10065	1.99736	2.59201	2.58873	2.45392	0.106065	0.0978884	0.111222	0.260806	0.247259	0.382996	0.0578883	0.0660172	0.0722657	0.0420013	0.0465555	0.0473981
567.83	0.984397	1.81062	0.331822	0.0882268	0.305938	0.758223	1.75844	0.334419	0.0580031	0.506551	-0.216744	2.76061	2.11321	2.01532	1.61971	2.27195	2.16094	1.99386	3.03926	3.07151	2.64935	0.70174	-0.395598	-0.391263	0.0635286	0.063638	0.0861011	0.0546479	0.057958	0.0650285	0.0522309	0.0579356	0.0704505	0.148851	0.269639	0.268813
528.366	0.983252	-0.0737502	0.00608814	-0.111246	6.58728	0.755214	0.00976601	0.0832116	-0.0323607	6.5914	-0.138167	2.99574	3.39248	3.21819	3.11485	3.44646	3.46818	3.24439	-2.7607	-1.38677	-1.42315	-4.85837	-4.77283	-4.82293	0.0625017	0.0685246	0.0800915	0.0552189	0.0574877	0.0622564	0.828644	0.575127	0.552206	0	0	0
390.258	0.977458	0.524935	-0.189583	-0.174068	7.50915	-0.708492	0.632999	-0.125792	-0.114003	7.43841	0.170245	-2.81676	4.23645	4.45859	4.65678	4.24953	4.27875	4.28665	-4.66021	-4.40882	-4.51574	-2.55077	-1.2523	-1.28597	0.0283733	0.0248943	0.0242616	0.0256193	0.0263947	0.0258143	0	0	0	0.941248	0.573779	0.599357
362.568	0.975778	1.32113	0.107125	-0.0726115	1.15306	0.367741	1.1981	0.112699	-0.0538296	1.79136	-0.866025	2.42889	1.91816	1.71041	1.32853	2.74095	2.52716	2.50006	1.23659	1.78339	1.61936	-1.24644	-0.901063	-1.0223	0.0639048	0.0720146	0.0986347	0.0399812	0.0457714	0.0462354	0.130131	0.107208	0.112346	0.375693	0.333752	0.370422
308.167	0.971624	-0.344148	0.0124653	-0.0806473	6.94361	0.787666	-0.241972	0.00826923	-0.0459071	6.88186	0.0750418	2.23745	3.31609	3.15476	3.25848	3.10546	3.27554	3.11669	-2.77958	-2.17845	-2.5651	-4.85837	-4.77283	-4.82293	0.0795346	0.0848387	0.085655	0.0779049	0.073707	0.0735336	0.587114	0.525423	0.640216	0	0	0
254.003	0.96578	0.769621	0.143988	-0.0381804	0.744619	1.06523	1.10987	0.0821817	-0.0625914	0.164665	0.141645	5.40793	1.4248	1.49064	0.954499	1.42421	1.00738	0.914071	2.87709	3.9783	4.97713	-1.72102	-1.67083	-2.3665	0.0872396	0.0863769	0.124264	0.0845001	0.107039	0.111622	0.0595583	0.0379189	0.0228907	0.497265	0.487603	0.673522
237.473	0.963485	-1.95031	-0.835227	-0.425627	0.535438	-0.161094	-2.05152	-0.745772	-0.441899	1.04508	1.37939	-3.38064	-1.8266	-0.381803	0.127393	-3.4617	-2.16648	-1.51857	-4.66021	-4.40882	-4.51574	-1.04955	-0.876653	-0.166896	0.323806	0.159625	0.142216	0.571907	0.361975	0.267456	0	0	0	1.04087	1.03406	0.754268
228.239	0.962064	3.51818	0.0825936	-0.13518	-1.03536	0.59237	3.59108	0.0617867	-0.133579	-1.38806	-0.31502	2.0569	2.71083	2.70045	2.76342	3.00901	3.3239	2.83973	5.12296	5.47876	5.51973	3.33806	3.37034	3.01386	0.053137	0.0524243	0.0576711	0.04187	0.0369759	0.0454144	0.0117734	0.0108204	0.010895	0.0265534	0.0246258	0.0312232
208.2	0.958563	0.662259	-0.157199	-0.177916	8.81334	0.712232	0.842568	-0.021466	-0.0708601	8.58222	0.0491437	2.71622	5.12517	5.20369	5.15671	5.09417	5.16278	5.08027	-3.78741	-1.94087	-1.54517	-4.85837	-4.77283	-4.82293	0.0178694	0.0179299	0.0190425	0.016556	0.0173681	0.018155	0.532587	0.357576	0.28392	0	0	0
169.036	0.949448	2.07825	0.181048	0.0427387	0.90335	-0.28288	1.97207	0.126875	-0.00708686	1.48308	1.36341	-2.43543	3.57082	3.65812	3.45299	2.89626	1.6512	1.26987	-0.239167	-0.163058	-0.249395	2.14183	2.70243	2.7437	0.0552025	0.0510247	0.0649265	0.0706448	0.140697	0.16904	0.215759	0.237532	0.242359	0.0590437	0.0465245	0.0472373


If I focus only on the eta1_* columns:
eta1_0	eta1_1	eta1_2
3.56875	0.325802	3.81669
6.27052	-0.178504	2.25072
-5.40029	2.43308	-0.980819
8.08109	-0.449734	4.4589
-1.39905	2.09433	-0.431892
0.506551	-0.216744	2.76061
6.5914	-0.138167	2.99574
7.43841	0.170245	-2.81676
1.79136	-0.866025	2.42889
6.88186	0.0750418	2.23745
0.164665	0.141645	5.40793
1.04508	1.37939	-3.38064
-1.38806	-0.31502	2.0569
8.58222	0.0491437	2.71622
1.48308	1.36341	-2.43543

I still have a hard time understanding how eta1_0 corresponds to eta1_1/eta1_1 (or I guess something like (ln(exp(eta1_1)/exp(eta1_2)):

eta1_0	ln(exp(eta1_1)/exp(eta1_2)
3.56875	-3.490888
6.27052	-2.429224
-5.40029	3.413899
8.08109	-4.908634
-1.39905	2.526222
0.506551	-2.977354
6.5914	-3.133907
7.43841	2.987005
1.79136	-3.294915
6.88186	-2.1624082
0.164665	-5.266285
1.04508	4.76003
-1.38806	-2.37192
8.58222	-2.6670763
1.48308	3.79884


Both the magnitude seems a bit off and the signs don't seem to agree (if anything it looks like eta1_0 corresponds to ln(exp(eta1_2)/exp(eta1_1) rather than ln(exp(eta1_1)/exp(eta1_2) in most cases but not all.

**Comment by eturro** [comment]
There is no assumed relationship between eta1_0 and eta1_1/eta1_2 ; I'm not sure why you thin there should be one. The interpretations are:

> eta1_0: log FC between group1 and group 2
> eta1_1: log FC between treatment and control in group 1
> eta1_2: log FC between treatment and control in group 2

The baseline model includes a fold change between group1 and group2 and the same fold change between treatment and control in both groups. Therefore, for high posterior probability features, what you would expect to see is that eta1_1 != eta1_2. That's about it... there isn't necessarily any relationship between these two parameters and eta1_0.

**Comment by ndrubins** [comment]
I guess what's not clear to me is what exactly is log FC between group1 and group 2 (eta1_0). Each group has treatment and control so which fold change is it referring to?

I thought that it is the fold change between the fold change in treatment and control between group1 and group2 - log((group1.treatment/group1.control)/(group2.treatment/group2.control)). This is why I expected it to correlate with eta1_1/eta1_2. And obviously it's absolute value should correlate with the Bayes factor and posterior probability.

Can you please clarify? 

Thanks a lot.

**Comment by eturro** [comment]
The parameter eta1_0 represents the mean difference between the two groups after adjusting for the other two parameters, which represent mean within group differences. This is the same as in any standard regression model. 

On another point, the Bayes factor and the posterior probability increase together monotonically so there is no reason to rank on one rather than the other.

**Comment by ndrubins** [comment]
Hi @eturro, I'm still not sure tha output makes sense to me. 
Maybe showing a few examples of what I'm getting will help better clarify my point.

As I described before I want to contrast the fold change of group1 treatment vs. group1 control (for which I have 3 samples per each condition) with that of group2 (also, 3 samples for the treatment and control).

My design matrix has 2 model independent effects that which are expressed in M:

# M; no. of rows = no. of observations
0.581926145 0.5706973218
0.3205125291 -0.815700053
-0.7474180092 0.0945409458
0.581926145 0.5706973218
0.3205125291 -0.815700053
-0.7474180092 0.0945409458
0.7006005139 0.3560338457
0.0228867125 -0.8773920953
-0.7131865943 0.3215944836
0.7006005139 0.3560338457
0.0228867125 -0.8773920953
-0.7131865943 0.3215944836
# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
0 0
1 1
1 1
1 1
2 2
2 2
2 2
3 3
3 3
3 3
# P0(collapsed); no. of rows = no. of classes for model 0
.5 .5
.5 -.5
-.5 .5
-.5 -.5
# P1(collapsed); no. of rows = no. of classes for model 1
.5 .5 0
.5 -.5 0
-.5 0 .5
-.5 0 -.5


I run mmdiff with this order of samples:
mmdiff -m design.matrix group1.treatment_1 group1.treatment_2 group1.treatment_3 group1.control_1 group1.control_2 group1.control_3 group2.treatment_2 group2.treatment_3 group2.control_1 group2.control_2 group2.control_3

Looking at the output, here are the first 4 genes (mouse ensembl accessions), where the output is ranked by Bayes factor and then posterior probability:

feature_id	bayes_factor	posterior_probability	alpha0	beta0_0	beta0_1	eta0_0	eta0_1	alpha1	beta1_0	beta1_1	eta1_0	eta1_1	eta1_2	mu_group1.treatment_1.collapsed.gene	mu_group1.treatment_2.collapsed.gene	mu_group1.treatment_3.collapsed.gene	mu_group1.control_1.collapsed.gene	mu_group1.control_2.collapsed.gene	mu_group1.control_3.collapsed.gene	mu_group2.treatment_1.collapsed.gene	mu_group2.treatment_2.collapsed.gene	mu_group2.treatment_3.collapsed.gene	mu_group2.control_1.collapsed.gene	mu_group2.control_2.collapsed.gene	mu_group2.control_3.collapsed.gene	sd_group1.treatment_1.collapsed.gene	sd_group1.treatment_2.collapsed.gene	sd_group1.treatment_3.collapsed.gene	sd_group1.control_1.collapsed.gene	sd_group1.control_2.collapsed.gene	sd_group1.control_3.collapsed.gene	sd_group2.treatment_1.collapsed.gene	sd_group2.treatment_2.collapsed.gene	sd_group2.treatment_3.collapsed.gene	sd_group2.control_1.collapsed.gene	sd_group2.control_2.collapsed.gene	sd_group2.control_3.collapsed.gene
ENSMUSG00000033478	31937.1	0.999718	2.28099	0.144247	-0.0908327	-0.224227	0.904204	2.21135	0.265091	-0.244551	-0.244484	6.77652	-0.108968	5.48348	6.08795	5.05621	-1.09697	-1.1167	-2.00496	2.20714	2.31734	2.40528	2.39074	2.34118	2.45806	0.018101	0.0157499	0.0228914	0.37534	0.381017	0.581046	0.0449727	0.0440391	0.0323173	0.0333484	0.0347926	0.0315308
ENSMUSG00000032323	17619.1	0.999489	1.31195	0.226549	-0.0366791	3.98508	-0.0580657	0.695709	0.0684895	0.0556213	5.97488	-1.32282	5.07102	3.10967	2.93801	2.99527	4.35945	4.30841	4.41684	0.621131	0.340096	-0.542506	-4.87648	-4.81239	-4.84959	0.0363921	0.0431454	0.0360488	0.0147497	0.015361	0.0145067	0.218596	0.246742	0.355425	0	0	0
ENSMUSG00000034918	15989.9	0.999437	-0.257819	-0.262362	-0.322329	3.66507	0.242543	-0.516627	-0.348253	-0.282207	5.14539	-1.40316	3.47052	0.884886	1.63841	1.47532	2.4409	2.77168	3.13017	-1.49067	-1.14648	-1.23359	-4.87648	-4.81239	-4.84959	0.114267	0.0849752	0.0809536	0.0409756	0.0336411	0.0287776	0.31811	0.296803	0.226698	0	0	0
ENSMUSG00000070473	15395.6	0.999416	-0.40238	-0.0569381	-0.0503557	4.25531	0.75798	-0.544958	-0.0446317	-0.0937315	4.84886	-0.0949774	3.7405	1.73806	1.90113	1.8736	1.85943	2.00396	1.93305	-1.09983	-1.28422	-0.930322	-4.87648	-4.81239	-4.84959	0.0885418	0.0875771	0.0757574	0.0617387	0.0603768	0.0619016	0.511507	0.60492	0.37798	0	0	0

![fam1601b](https://cloud.githubusercontent.com/assets/1158174/26038171/f36792bc-38b6-11e7-818b-90392d052ae1.png)
![cldn3](https://cloud.githubusercontent.com/assets/1158174/26038172/fc518644-38b6-11e7-9e34-a0f579f9390d.png)
![cdhr2](https://cloud.githubusercontent.com/assets/1158174/26038173/fc5307d0-38b6-11e7-9290-f929a8a2f87d.png)
![cyp11a1](https://cloud.githubusercontent.com/assets/1158174/26038175/fca303fc-38b6-11e7-94bd-78b9ddb549b6.png)

The figures show the expression levels of these four genes, where from left to right are:
group1 treatment samples, group1 control samples, group2 treatment samples, group2 control samples.

For Fam160b1:ENSMUSG00000033478 eta1_0 is -0.244484 however the group1 treatment/group1 control to group2 treatment/group2 control, first of all is > 1 and hence should be positive rather than negative, but more importantly seems much higher than 0.244484.

For Cyp11a1:ENSMUSG00000032323 the fold seems to go in the opposite direction but eta1_0=5.97488 is now positive and much larger, although the effect in Fam160b1 seems much larger to me

For Cldn3:ENSMUSG00000070473 the fold change seems much smaller but still the Bayes factor is very high and again eta1_0=4.84886 has the opposite sign and seems much larger than should be.


I'd greatly appreciate your help

**Comment by eturro** [comment]
Your plots are a good way of representing the normalised mmseq output. I assume you are showing the mu_ values +/- the corresponding sd_* values in the mmdiff output table.


> For Fam160b1:ENSMUSG00000033478 eta1_0 is -0.244484 however the group1 treatment/group1 control to group2 treatment/group2 control, first of all is > 1 and hence should be positive rather than negative, but more importantly seems much higher than 0.244484.

If the sign of eta1_0 is positive, then the mean expression in group1 is greater than in group 2.

Looking at your first plot, the mean seems very similar in the two groups (approximately =2) but it is slightly lower in group 1 than group 2, which is why the eta1_0 estimate has a negative sign.

> 
> For Cyp11a1:ENSMUSG00000032323 the fold seems to go in the opposite direction but eta1_0=5.97488 is now positive and much larger, although the effect in Fam160b1 seems much larger to me

This value makes perfect sense. The mean expression in group1 is (green and orange) much greater than in group 2 (blue and pink)

> 
> For Cldn3:ENSMUSG00000070473 the fold change seems much smaller but still the Bayes factor is very high and again eta1_0=4.84886 has the opposite sign and seems much larger than should be.

This value makes perfect sense. The mean expression in group1 is (green and orange) much greater than in group 2 (blue and pink)


Don't forget that a high posterior probability is obtained when green - orange != blue - pink.

In all of your plots it seems quite clear that the difference between green and orange is different than the difference between blue and pink

**Comment by ndrubins** [comment]
Thanks for your help @eturro. I guess I was confused about eta1_0, thinking it explicitly estimates the fold change over the fold change, which makes it interpretable in the context of the question this model is used for. 

Given that, should I just take ln(exp(eta1_1)/exp(eta1_2)) to represent the estimated fold change over the fold change between group1 and group2, respectively?

**Comment by eturro** [comment]
Just use eta1_2-eta1_1 (assuming posterior_probability is high)

**Comment by ndrubins** [comment]
Thanks

**Comment by eturro** [comment]
No problem. Best of luck with your work.
