### ISSUE TITLE
How to run haploref.rb

### ISSUE THREAD

**Issue by weishwu** [eturro/mmseq#29]
Could someone explain how to prepare the inputs ("pos_file" and "hap_file") to run haploref.rb?
The manual just says:

>   pos_file: file containing, for each transcript, chromosome and positions of SNPs.
>   hap_file: file containing, for each transcript, two versions, e.g. suffixed _A and _B, on separate lines with the alleles for the two haplotypes at each position listed in the pos_file (A and B respectively).

Should I used genomic coordinates of the SNPs? Suppose I have the following transcript and SNPs:
```
ENST00000450305.2 (chr1 12010-13670)
chr1 12020 A T (in exon1; phased genotype is 0|1)
chr1 13300 G C (in exon5; phased genotype is 0|1)
```

Is the following correct?

```
#Pos_file:
ENST00000450305.2
chr1 12020
chr1 13300
```

```
#Hap_file
ENST00000450305.2_A
A
G
ENST00000450305.2_B
T
C
```

Thanks.

**Comment by eturro** [comment]
There should be one entry per transcript:
```
#Pos_file:
ENST00000450305.2 chr1 12020 13300
...
```
```
#Hap_file:
ENST00000450305.2_A AG
ENST00000450305.2_B TC
...
```
