### ISSUE TITLE
How to calculate ASE significance from MMSeq outputs

### ISSUE THREAD

**Issue by weishwu** [eturro/mmseq#33]
I've run alignment against a diploid transcriptome and used MMSeq to quantify expression on each of the two haplotypes for each transcript. How to calculate a p-value for allele specific expression (ASE)?

**Comment by eturro** [comment]
Let's say the transcript IDs for the two haplotypes are suffixed _A and _B respectively. You need to split each *mmseq file in two files, each containing a two-line header, followed by the entries for a particular strain. Remove all the suffixes from these files, then run mmdiff to obtain posterior probabilities of differential expression. E.g. mmdiff -de 3 3 haploA_sample1.mmseq  haploA_sample2.mmseq haploA_sample3.mmseq haploB_sample1.mmseq haploB_sample2.mmseq haploB_sample3.mmseq
