### ISSUE TITLE
Wrong tag 10.0.10a?

### ISSUE THREAD

**Issue by junaruga** [eturro/mmseq#41]
Seeing history of tags https://github.com/eturro/mmseq/tags here,

Tag 1.0.10 released at Fed 16 2017.
Tag 10.0.10a released at Feb 25 2019.

`10.0.10a` is wrong. `1.0.10a` is correct, right?
If it is wrong, could you modify the tag information?

Thank you.

**Comment by junaruga** [comment]
https://github.com/eturro/mmseq/commit/7e9cbc43081b5abb1faa3b2f79e07c26eca8cb55

```
diff --git a/src/VERSION b/src/VERSION
index 66c4c22..81c871d 100644
--- a/src/VERSION
+++ b/src/VERSION
@@ -1 +1 @@
-1.0.9
+1.10.0
```

This comment is wrong, isn't it?

`1.10.0` is wrong. `1.0.10a` is correct, right?

**Comment by junaruga** [comment]
```
$ git tag -n
1.0.10          MMSEQ package 1.0.10
1.0.2           MMSEQ version 1.0.2
1.0.3           MMSEQ version 1.0.3
1.0.4           MMSEQ package 1.0.4
1.0.5           MMSEQ package 1.0.5
1.0.6           MMSEQ package 1.0.6
1.0.7           MMSEQ package 1.0.7
1.0.8           MMSEQ package 1.0.8
1.0.8a          MMSEQ package 1.0.8a
1.0.9           1.0.9
10.0.10a        MMSEQ package 1.0.10a
latest          MMSEQ package 1.0.10a
```

Seeing following line, the tag comment `MMSEQ package 1.0.10a` looks right. Only actual tag `10.0.10a` is wrong.

```
10.0.10a        MMSEQ package 1.0.10a
```

**Comment by junaruga** [comment]
How about adding below kind of script to add git tag operation to avoid a mistake?
I have not tested the script.

release_tag.sh

```
#!/bin/bash

set -ex

VERSION=$1
echo "${VERSION}" > src/VERSION
git add src/VERSION
git commit -m "MMSEQ package ${VERSION}".
git tag -a "${VERSION}" -m 'MMSEQ package ${VERSION}'

git push origin master
git push origin "${VERSION}"
```

```
$ ./release_tag.sh 1.0.10a
```

**Comment by eturro** [comment]
Fixed, thank you
