### ISSUE TITLE
mmdiff index out of bounds error

### ISSUE THREAD

**Issue by jjenny** [eturro/mmseq#47]
Hi,

When I try to run mmdiff it gets through printing out the log scale normalisation factors and then it terminates with this error:

terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::col(): index out of bounds
Aborted

Any ideas?

Thanks!

**Comment by eturro** [comment]
Hi Jenny, could you please make the input files available to me and tell me the precise command you ran?

**Comment by jjenny** [comment]
Yes, the command I ran is:

` ~/bin/mmseq-1.0.10a/bin/mmdiff -m cons_vs_cis.design_matrix.txt Parentals/BW_14_01.mmseq.gene.mmseq  Parentals/BW_14_02.mmseq.gene.mmseq  Parentals/BW_14_13.mmseq.gene.mmseq  Parentals/BW_14_16.mmseq.gene.mmseq  Parentals/BW_14_28.mmseq.gene.mmseq  Parentals/BW_14_29.mmseq.gene.mmseq Parentals/NB_14_04.mmseq.gene.mmseq  Parentals/NB_14_05.mmseq.gene.mmseq  Parentals/NB_14_14.mmseq.gene.mmseq  Parentals/NB_14_15.mmseq.gene.mmseq  Parentals/NB_14_24.mmseq.gene.mmseq  Parentals/NB_14_38.mmseq.gene.mmseq F1Hybrids/F1_14_S13.mmseq.gene.mmseq.BW  F1Hybrids/F1_14_S16.mmseq.gene.mmseq.BW  F1Hybrids/F1_14_S2.mmseq.gene.mmseq.BW  F1Hybrids/F1_14_S7.mmseq.gene.mmseq.BW  F1Hybrids/F1_14_S8.mmseq.gene.mmseq.BW  F1Hybrids/F1_14_S9.mmseq.gene.mmseq.BW F1Hybrids/F1_14_S13.mmseq.gene.mmseq.NB  F1Hybrids/F1_14_S16.mmseq.gene.mmseq.NB  F1Hybrids/F1_14_S2.mmseq.gene.mmseq.NB  F1Hybrids/F1_14_S7.mmseq.gene.mmseq.NB  F1Hybrids/F1_14_S8.mmseq.gene.mmseq.NB  F1Hybrids/F1_14_S9.mmseq.gene.mmseq.NB > p14.mmdiff`

The design matrix is:
[cons_vs_cis.design_matrix.txt](https://github.com/eturro/mmseq/files/4299787/cons_vs_cis.design_matrix.txt)

An example mmseq output file (I checked that all the mmseq output files have the same number of rows and colums):

[F1_14_S2.mmseq.gene.mmseq.BW.txt](https://github.com/eturro/mmseq/files/4299791/F1_14_S2.mmseq.gene.mmseq.BW.txt)

Thanks,

Jenny

**Comment by eturro** [comment]
Sorry the error wasn't very informative.

The C matrix needs to include two columns, one for each model being compared.

In your case, I assume you have the same grouping of samples into classes, so you'd want to repeat the column twice, i.e.

# C; no. of rows = no. of observations and no. of columns = 2 (one for each model)
0 0
0 0
0 0
0 0
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1
2 2
2 2
2 2
2 2
2 2
2 2
3 3
3 3
3 3
3 3
3 3
3 3

**Comment by jjenny** [comment]
It works now - thanks!
