### ISSUE TITLE
How to run MMDIFF to perform Bayesian polytomous model using raw reads count matrix as input?

### ISSUE THREAD

**Issue by farhan-lab** [eturro/mmseq#51]
Dear mmseq developer,

Thank you for the great tool. I was wondering whether I can run MMDIFF tool on data input as raw reads count? My data is a raw reads count table, in which each row is a gene and each column represents reads counts for sample. I want to compare different modes of differential expression patterns by comparing multiple cell types, for example like [this paper](https://www.science.org/doi/10.1126/science.1251033?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed). 

Thank you,
Best,
Farhan

**Comment by eturro** [comment]
Hi, you need to run bowtie (version 1) and mmseq as per the instructions on the github page before you can run mmdiff.
