### ISSUE TITLE
mmcollapse-linux error: arma::memory::acquire(): out of memory

### ISSUE THREAD

**Issue by john321123** [eturro/mmseq#8]
Hello
I try to learn this paper (http://dx.doi.org/10.7554/eLife.07860.001), to find imprinting gene.

I use mmcollapse-linux combining transcripts, but

##########################
mmcollapse-linux tpm_MR1000Aligned tpm_MR1312Aligned
Stopping threshold: -97.5th percentile of the distribution of correlations
tpm_MR1000Aligned SD thres=1.33026
tpm_MR1312Aligned SD thres=1.31731
73716 transcripts or sets of identical transcripts are unidentifiable in all samples.

error: arma::memory::acquire(): out of memory

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
#############################

what's wrong with it?

**Comment by ttriche** [comment]
you need to buy more RAM


--t

**Comment by john321123** [comment]
Server configuration is as follows：
cpu32 cores

**Comment by john321123** [comment]
thank you ,but the error is the same

############################
Server configuration is as follows:
cpu: 32cores
mem:48GB swap:24GB

and other sever:
ncpus=40,
physmem=528642184kb,
availmem=450372140kb,
totmem=559358456kb
###############################

the input file like this:
12M Jan  8 20:13 tpm_MR1000Aligned.gene.mmseq
2.5M Jan  8 20:13 tpm_MR1000Aligned.identical.mmseq
341 Jan  8 17:26 tpm_MR1000Aligned.identical.mmseq.R
44M Jan  8 20:13 tpm_MR1000Aligned.mmseq
######
log_mu：log(fpkm) replaced by log(tpm)
tpm_MR1000Aligned.identical.mmseq

feature_id      log_mu  sd      mcse    iact    effective_length        true_length     unique_hits     observed        ntranscripts    percentiles5.25.50.75.95
ENSMUST00000098042.8_maternal+ENSMUST00000098042.8_paternal     -4.60517018598809       10.0714 0       NA      713.998 984     0       0       2       NA,NA,NA,NA,NA
ENSMUST00000146643.1_maternal+ENSMUST00000146643.1_paternal     -1.61721677628831       0.742345        0.0221155       0.908828        550.999 821     2       1       2
ENSMUST00000177665.1_maternal+ENSMUST00000177665.1_paternal     -4.60517018598809       10.0714 0       NA      1230    1500    0       0       2       NA,NA,NA,NA,NA
ENSMUST00000178312.1_maternal+ENSMUST00000178312.1_paternal     -4.60517018598809       10.0714 0       NA      1230    1500    0       0       2       NA,NA,NA,NA,NA
######
It requires a lot of memory? Or other problems.

**Comment by eturro** [comment]
Hi

Sorry, but it really does require a lot of memory. It needs to store 1024 X number of samples X number of features as doubles. I believe mmcollapse gives you an estimate of how much memory is required at the start.

It might be best if you skip this step for now if you don't have a very high memory machine available and go straight to mmdiff. 

Are you interested mainly in gene-level imprinting rather than transcript-level imprinting? If so the collapsing can be skipped without much detriment.

I have been trying to find a way to reduce the memory footprint of mmcollapse but it's not entirely straightforward. 

Best wishes
Ernest

**Comment by john321123** [comment]
Thank you for your answer.

I interested mainly in gene-level imprinting. Although the paper is based on transcripts, BRAIN model  to estimates expression levels of transcripts.

I will try mmdiff

**Comment by snijesh** [comment]
`ls()`
remove unwanted items from `ls()`
rm('itemname')
set memory limit
`memory.limit(9999999)`
